//.github/workflows/deploy.yml

name: CD Pipeline # Name of the workflow

on:
  push: # Trigger the workflow on push events
    branches:
      - master # Only run for pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Check out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Set up Node.js environment
        with:
          node-version: '14' # Specify Node.js version to use

      - name: Install dependencies
        run: npm install # Install project dependencies

      - name: Build project
        run: npm run build # Build the project

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # Configure AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key ID from secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Access Key from secrets
          aws-region: us-west-2 # AWS region

      - name: Deploy to S3
        run: aws s3 sync build/ s3://my-s3-bucket --delete # Sync the build directory to the S3 bucket
